Get measurements
SMAIA-X/smaiax-backend pull request #87
Opened 2024-12-08 12:23 UTC by 1r-1na

2024-12-12 14:12 UTC, Smightym8 requested changes

2024-12-12 14:12 UTC, Smightym8 commented on src/SMAIAXBackend.API/Endpoints/Measurement/GetMeasurementsEndpoint.cs
> +            await measurementListService.GetFilteredMeasurementsByTenantAndSmartMeterAsync(
Rename `GetFilteredMeasurementsByTenantAndSmartMeterAsync` to `GetFilteredMeasurementsBySmartMeterAsync`.

2024-12-12 14:12 UTC, Smightym8 commented on src/SMAIAXBackend.API/Middlewares/ExceptionHandlerMiddleware.cs
> +            case ArgumentException:
Remove the `ArgumentException` and use only custom exceptions here.

2024-12-12 14:12 UTC, Smightym8 commented on src/SMAIAXBackend.Application/Services/Implementations/MeasurementListService.cs
> +    public async Task<List<MeasurementRawDto>> GetFilteredMeasurementsByTenantAndSmartMeterAsync(
Rename `GetFilteredMeasurementsByTenantAndSmartMeterAsync` to `GetFilteredMeasurementsBySmartMeterAsync`.

2024-12-12 14:12 UTC, Smightym8 commented on src/SMAIAXBackend.Application/Services/Interfaces/IMeasurementListService.cs
> +    Task<List<MeasurementRawDto>> GetFilteredMeasurementsByTenantAndSmartMeterAsync(Guid smartMeterId,
Rename `GetFilteredMeasurementsByTenantAndSmartMeterAsync` to `GetFilteredMeasurementsBySmartMeterAsync`.

2024-12-12 14:12 UTC, Smightym8 commented on src/SMAIAXBackend.Domain/Repositories/IMeasurementRepository.cs
> +    Task<List<Measurement>> GetMeasurementsByTenantAndSmartMeterAsync(SmartMeterId smartMeterId,
Rename `GetMeasurementsByTenantAndSmartMeterAsync` to `GetMeasurementsBySmartMeterAsync`.

2024-12-12 14:12 UTC, Smightym8 commented on src/SMAIAXBackend.Infrastructure/Repositories/MeasurementRepository.cs
> +        if (endAt > startAt)
Move this check to the application service and throw a custom exception.

2024-12-12 14:12 UTC, Smightym8 commented on src/SMAIAXBackend.Infrastructure/Repositories/MeasurementRepository.cs
> +        endAt ??= startAt?.AddDays(-1) ?? DateTime.UtcNow.AddDays(-1);
Move this to the application service.

2024-12-17 16:20 UTC, 1r-1na commented on src/SMAIAXBackend.Infrastructure/Repositories/MeasurementRepository.cs
> +        endAt ??= startAt?.AddDays(-1) ?? DateTime.UtcNow.AddDays(-1);
I disabled the automatic range to one day and made startAt and endAt required.

2024-12-17 21:16 UTC, Smightym8 approved these changes

2024-12-18 10:39 UTC, merged